version: '3'
services:
  postgres:
    image: postgres:alpine
    hostname: postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ECE9014
    volumes:
      - ./csv:/csv
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
volumes:
  postgres-data:
